export const SET_USER="SET_USER";
export const SET_AUTHENTICATED="SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED="SET_UNAUTHENTICATED";
export const LOADING_USER="LOADING_USER";
export const MARK_NOTIFICATIONS_READ="MARK_NOTIFICATIONS_READ";