export const SET_USER="SET_USER";
export const SET_AUTHENTICATED="SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED="SET_UNAUTHENTICATED";
export const LOADING_USER="LOADING_USER";
export const LIKE_SCREAM="LIKE_SCREAM";
export const UNLIKE_SCREAM="UNLIKE_SCREAM";
